version: '3'

services:
  netflixdb:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'netflixdb'
    restart: always
    volumes:
      - netflixdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jklv1234

volumes:
  netflixdb-data:
